"""
Auto-fix generator.

Turns deterministic WCAG failures into concrete CSS/HTML patches. Only generates
fixes for issues where the correct answer is mechanical (contrast ratios, target
sizes, missing labels, lang attribute, landmarks, heading hierarchy). Subjective
issues are left alone.

Output is two artefacts:
- fixes.css: an override stylesheet the user can drop into their project
- fixes.md: HTML snippets and structural changes the user must apply by hand

The CSS selectors come from the DOM extractor's "element" field, which is a
tag + first-class combination. These are best-effort locators and may need
manual verification — we flag this in the output.
"""

from __future__ import annotations

from dataclasses import dataclass, field


# ── Colour maths (duplicated here to avoid coupling to extractor JS) ──


def _parse_color(value: str) -> tuple[int, int, int] | None:
    """Parse a hex or rgb()/rgba() colour into an (r, g, b) tuple."""
    if not value:
        return None
    v = value.strip().lower()
    if v.startswith("#"):
        v = v[1:]
        if len(v) == 3:
            v = "".join(c * 2 for c in v)
        if len(v) == 6:
            try:
                return int(v[0:2], 16), int(v[2:4], 16), int(v[4:6], 16)
            except ValueError:
                return None
        return None
    if v.startswith("rgb"):
        inside = v[v.find("(") + 1 : v.find(")")]
        parts = [p.strip() for p in inside.split(",")]
        if len(parts) >= 3:
            try:
                return int(float(parts[0])), int(float(parts[1])), int(float(parts[2]))
            except ValueError:
                return None
    return None


def _to_hex(rgb: tuple[int, int, int]) -> str:
    r, g, b = (max(0, min(255, int(c))) for c in rgb)
    return f"#{r:02x}{g:02x}{b:02x}"


def _relative_luminance(rgb: tuple[int, int, int]) -> float:
    def channel(c: int) -> float:
        s = c / 255.0
        return s / 12.92 if s <= 0.03928 else ((s + 0.055) / 1.055) ** 2.4

    r, g, b = rgb
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def _contrast_ratio(a: tuple[int, int, int], b: tuple[int, int, int]) -> float:
    la = _relative_luminance(a)
    lb = _relative_luminance(b)
    lighter, darker = max(la, lb), min(la, lb)
    return (lighter + 0.05) / (darker + 0.05)


def _adjust_to_ratio(
    text_rgb: tuple[int, int, int],
    bg_rgb: tuple[int, int, int],
    target_ratio: float,
) -> tuple[int, int, int]:
    """Shift the text colour toward black or white until it hits target ratio.

    Chooses the direction (darker/lighter) that the background's luminance
    implies: light backgrounds get darker text, dark backgrounds get lighter
    text. Interpolates in RGB space toward the endpoint.
    """
    bg_l = _relative_luminance(bg_rgb)
    # On light backgrounds push text toward black; on dark, toward white.
    toward = (0, 0, 0) if bg_l > 0.5 else (255, 255, 255)

    # Binary search on the interpolation factor t ∈ [0, 1].
    lo, hi = 0.0, 1.0
    best = text_rgb
    for _ in range(24):
        t = (lo + hi) / 2
        candidate = (
            round(text_rgb[0] + (toward[0] - text_rgb[0]) * t),
            round(text_rgb[1] + (toward[1] - text_rgb[1]) * t),
            round(text_rgb[2] + (toward[2] - text_rgb[2]) * t),
        )
        if _contrast_ratio(candidate, bg_rgb) >= target_ratio:
            best = candidate
            hi = t
        else:
            lo = t
    return best


# ── Fix data model ──


@dataclass
class CssFix:
    selector: str
    declarations: dict[str, str]
    reason: str
    criterion: str

    def to_css(self) -> str:
        body = "\n".join(f"  {k}: {v};" for k, v in self.declarations.items())
        return f"/* {self.criterion}: {self.reason} */\n{self.selector} {{\n{body}\n}}"


@dataclass
class HtmlFix:
    title: str
    criterion: str
    before: str
    after: str
    notes: str = ""

    def to_markdown(self) -> str:
        parts = [f"### {self.title}", f"_{self.criterion}_", ""]
        if self.before:
            parts += ["**Before:**", "```html", self.before, "```", ""]
        parts += ["**After:**", "```html", self.after, "```"]
        if self.notes:
            parts += ["", self.notes]
        return "\n".join(parts)


@dataclass
class FixSet:
    css_fixes: list[CssFix] = field(default_factory=list)
    html_fixes: list[HtmlFix] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)

    @property
    def total(self) -> int:
        return len(self.css_fixes) + len(self.html_fixes)

    def to_css_file(self) -> str:
        if not self.css_fixes:
            return "/* No deterministic CSS fixes generated. */\n"
        header = (
            "/* Auto-generated by design-intel fix.\n"
            " * Drop this stylesheet into your project AFTER your main CSS so these\n"
            " * rules override the originals. Selectors are best-effort — verify each\n"
            " * rule matches the intended element before shipping.\n"
            " */\n\n"
        )
        return header + "\n\n".join(f.to_css() for f in self.css_fixes) + "\n"

    def to_markdown(self) -> str:
        lines = [
            "# Auto-Fix Report",
            "",
            f"Generated {len(self.css_fixes)} CSS fixes and {len(self.html_fixes)} "
            "HTML/structural fixes.",
            "",
        ]

        if self.css_fixes:
            lines += [
                "## CSS Fixes",
                "",
                "Saved to `fixes.css`. Include after your main stylesheet.",
                "",
                "| # | Selector | Criterion | Change |",
                "|---|----------|-----------|--------|",
            ]
            for i, f in enumerate(self.css_fixes, 1):
                change = ", ".join(f"{k}: {v}" for k, v in f.declarations.items())
                lines.append(f"| {i} | `{f.selector}` | {f.criterion} | {change} |")
            lines.append("")

        if self.html_fixes:
            lines += ["## HTML / Structural Fixes", ""]
            for f in self.html_fixes:
                lines.append(f.to_markdown())
                lines.append("")

        if self.skipped:
            lines += ["## Skipped (non-deterministic)", ""]
            for s in self.skipped:
                lines.append(f"- {s}")
            lines.append("")

        return "\n".join(lines)


# ── Per-criterion fix generators ──


def _fix_contrast(wcag_result, fixes: FixSet) -> None:
    """Darken or lighten text to meet the required contrast ratio."""
    for v in wcag_result.violations:
        issue = v.get("issue", "")
        # Parse "colorA on colorB = X:1 (requires Y:1)"
        required = 4.5
        if "requires" in issue:
            try:
                required = float(issue.split("requires")[1].split(":")[0].strip())
            except (ValueError, IndexError):
                pass

        # Extract the two colours from the issue string (colA on colB = ...)
        text_color = None
        bg_color = None
        if " on " in issue and " = " in issue:
            try:
                left = issue.split(" = ")[0]
                text_color, bg_color = left.split(" on ")
                text_color = text_color.strip()
                bg_color = bg_color.strip()
            except ValueError:
                pass

        text_rgb = _parse_color(text_color) if text_color else None
        bg_rgb = _parse_color(bg_color) if bg_color else None
        if not text_rgb or not bg_rgb:
            fixes.skipped.append(
                f"Contrast fix for `{v.get('element', '?')}` — could not parse colours"
            )
            continue

        new_rgb = _adjust_to_ratio(text_rgb, bg_rgb, required)
        new_hex = _to_hex(new_rgb)
        new_ratio = round(_contrast_ratio(new_rgb, bg_rgb), 2)

        selector = v.get("element", "").strip()
        if not selector:
            continue
        fixes.css_fixes.append(
            CssFix(
                selector=selector,
                declarations={"color": new_hex},
                reason=(
                    f'text on "{v.get("text", "")[:30]}" was '
                    f"{_to_hex(text_rgb)} → {new_hex} "
                    f"(ratio {v.get('ratio')} → {new_ratio}, requires {required})"
                ),
                criterion=wcag_result.criterion,
            )
        )


def _fix_non_text_contrast(wcag_result, fixes: FixSet) -> None:
    """Add a 1px border with sufficient contrast against the adjacent surface."""
    for v in wcag_result.violations:
        selector = v.get("element", "").strip()
        if not selector:
            continue
        issue = v.get("issue", "")
        # "componentBg vs adjacentBg = ratio:1"
        adjacent_rgb = None
        if " vs " in issue and " = " in issue:
            try:
                _, rest = issue.split(" vs ", 1)
                adjacent_hex = rest.split(" = ")[0].strip()
                adjacent_rgb = _parse_color(adjacent_hex)
            except ValueError:
                pass

        # Pick black or white border depending on adjacent luminance.
        if adjacent_rgb:
            border = "#1a1a1a" if _relative_luminance(adjacent_rgb) > 0.5 else "#e5e5e5"
        else:
            border = "#6b7280"  # neutral-500, 4.6:1 on white, 3.2:1 on #111

        fixes.css_fixes.append(
            CssFix(
                selector=selector,
                declarations={"border": f"1px solid {border}"},
                reason="add boundary so component meets 3:1 non-text contrast",
                criterion=wcag_result.criterion,
            )
        )


def _fix_target_size(wcag_result, fixes: FixSet) -> None:
    """Enforce 24x24 minimum with min-width/min-height + padding."""
    seen: set[str] = set()
    for v in wcag_result.violations:
        selector = v.get("element", "").strip()
        if not selector or selector in seen:
            continue
        seen.add(selector)
        size = v.get("size", "")
        # Parse "WxHpx"
        w = h = 0
        try:
            dims = size.replace("px", "").split("x")
            w, h = int(dims[0]), int(dims[1])
        except (ValueError, IndexError):
            pass

        declarations = {
            "min-width": "24px",
            "min-height": "24px",
        }
        # If element is close but short on padding, add inline-block sizing.
        if w < 24 or h < 24:
            declarations["box-sizing"] = "border-box"
            declarations["padding"] = "8px"

        fixes.css_fixes.append(
            CssFix(
                selector=selector,
                declarations=declarations,
                reason=f"was {size}, below 24×24 minimum",
                criterion=wcag_result.criterion,
            )
        )


def _fix_language(wcag_result, fixes: FixSet) -> None:
    fixes.html_fixes.append(
        HtmlFix(
            title="Add lang attribute to <html>",
            criterion=wcag_result.criterion,
            before='<html>',
            after='<html lang="en">',
            notes="Use the appropriate IETF language tag for your page content.",
        )
    )


def _fix_skip_link(wcag_result, fixes: FixSet) -> None:
    fixes.html_fixes.append(
        HtmlFix(
            title="Add skip-to-main link",
            criterion=wcag_result.criterion,
            before="<body>\n  <header>…</header>",
            after=(
                '<body>\n'
                '  <a href="#main" class="skip-link">Skip to main content</a>\n'
                '  <header>…</header>\n'
                '  <main id="main">…</main>'
            ),
            notes=(
                "Pair with CSS: `.skip-link { position:absolute; left:-9999px; } "
                ".skip-link:focus { left:0; top:0; }`"
            ),
        )
    )


def _fix_landmarks(wcag_result, fixes: FixSet) -> None:
    missing = [v.get("element", "") for v in wcag_result.violations]
    if not missing:
        return
    # Wrap tag names in backticks so markdown renderers don't eat the angle brackets.
    missing_display = ", ".join(f"`{m}`" for m in missing if m)
    fixes.html_fixes.append(
        HtmlFix(
            title=f"Add missing landmarks: {missing_display}",
            criterion=wcag_result.criterion,
            before="<div class='header'>…</div>\n<div class='content'>…</div>",
            after="<header>…</header>\n<nav>…</nav>\n<main>…</main>\n<footer>…</footer>",
            notes="Replace equivalent <div>s with semantic landmarks so assistive tech can navigate.",
        )
    )


def _fix_headings(wcag_result, fixes: FixSet) -> None:
    issues = [v.get("issue", "") for v in wcag_result.violations]
    fixes.html_fixes.append(
        HtmlFix(
            title="Fix heading hierarchy",
            criterion=wcag_result.criterion,
            before="",
            after="",
            notes="Issues found:\n" + "\n".join(f"- {i}" for i in issues if i),
        )
    )


def _fix_form_labels(wcag_result, fixes: FixSet) -> None:
    if not wcag_result.violations:
        return
    examples = []
    for v in wcag_result.violations[:5]:
        el = v.get("element", "input")
        issue = v.get("issue", "")
        # Try to extract placeholder for a starting label text.
        label_text = "Label"
        if 'placeholder: "' in issue:
            try:
                label_text = issue.split('placeholder: "')[1].split('"')[0] or "Label"
            except IndexError:
                pass
        examples.append((el, label_text, issue))

    before = "\n".join(f'<input ...>  <!-- {i} -->' for _, _, i in examples)
    after = "\n".join(
        f'<label for="field-{n}">{text}</label>\n<input id="field-{n}" ...>'
        for n, (_, text, _) in enumerate(examples, 1)
    )
    fixes.html_fixes.append(
        HtmlFix(
            title=f"Label {len(wcag_result.violations)} form input(s)",
            criterion=wcag_result.criterion,
            before=before,
            after=after,
            notes=(
                "Each input needs a programmatic label: wrap with <label>, use "
                "`for`/`id`, or add `aria-label` / `aria-labelledby` when a "
                "visible label is not possible."
            ),
        )
    )


# Map WCAG criterion substrings to fix generators.
_DISPATCH = [
    ("Contrast (Minimum)", _fix_contrast),
    ("Non-text Contrast", _fix_non_text_contrast),
    ("Target Size (Minimum)", _fix_target_size),
    ("Language of Page", _fix_language),
    ("Bypass Blocks", _fix_skip_link),
    ("Landmarks", _fix_landmarks),
    ("Headings", _fix_headings),
    ("Form Labels", _fix_form_labels),
]


def generate_fixes(wcag_report) -> FixSet:
    """Produce CSS + HTML fixes for all failing deterministic WCAG criteria."""
    fixes = FixSet()
    for result in wcag_report.results:
        if result.status != "fail":
            continue
        for needle, handler in _DISPATCH:
            if needle in result.criterion:
                handler(result, fixes)
                break
        else:
            fixes.skipped.append(
                f"{result.criterion} — no deterministic fix recipe available"
            )
    return fixes
